// Generated by 'unplugin-auto-import'
export {}
declare global {
  const FunctionComponent: typeof import('preact')['FunctionComponent']
  const clsx: typeof import('clsx')['clsx']
  const movieRoutePatten: typeof import('./src/hooks/useMediaRoute')['movieRoutePatten']
  const tvRoutePatten: typeof import('./src/hooks/useMediaRoute')['tvRoutePatten']
  const useCallback: typeof import('preact/hooks')['useCallback']
  const useContext: typeof import('preact/hooks')['useContext']
  const useEffect: typeof import('preact/hooks')['useEffect']
  const useEffectOnce: typeof import('react-use')['useEffectOnce']
  const useMediaType: typeof import('./src/hooks/useMediaRoute')['useMediaType']
  const useMemo: typeof import('preact/hooks')['useMemo']
  const useObserver: typeof import('./src/hooks/useObserver')['useObserver']
  const useReducer: typeof import('preact/hooks')['useReducer']
  const useRef: typeof import('preact/hooks')['useRef']
  const useState: typeof import('preact/hooks')['useState']
}
